### ISSUE TITLE
How to disable Device Preview

### ISSUE THREAD

**Issue by ilmalte** [imaNNeo/flappy_dash#3]
Hey @imaNNeo, I am opening this issue on behalf of @Ochko0310 who asked you this question in an issue on [namaka/dart](https://github.com/heroiclabs/nakama-dart).

![Screenshot 2024-12-09 154905](https://github.com/user-attachments/assets/01650a8f-fa01-4fe8-8c67-4b22b40e4c2a)

**Comment by ilmalte** [comment]
@Ochko0310 just go to https://github.com/imaNNeo/flappy_dash/blob/main/lib/main.dart and remove the widget devicepreview.

this
```dart
  runApp(DevicePreview(
    enabled: kDebugMode,
    builder: (context) => const MyApp(),
  ));
```
will be
```dart
  runApp(const MyApp());
```

more info here https://pub.dev/packages/device_preview

**Comment by imaNNeo** [comment]
Hi @ilmalte 
Thanks for explaining it. You're right.
There's also an option to pass `enabled: false,` in the DevicePreview to make it disabled.
```dart
runApp(DevicePreview(
  enabled: false,
  builder: (context) => const MyApp(),
));
  ```
